# Change these first
owner: tsolenthaler # Your GitHub organization or username, where this repository lives
repo: DashboardWebsitesTSO # The name of this repository

sites:
  - name: Appenzeller Bahnen
    url: https://appenzellerbahnen.ch
  - name: St. Gallen Bodensee
    url: https://st.gallen-bodensee.ch
  - name: Glarnerland
    url: https://glarnerland.ch
  - name: Thurgau Bodensee
    url: https://thurgau-bodensee.ch
  - name: Heidiland
    url: https://heidiland.com
  - name: Liechtenstein 
    url: https://tourismus.li
  - name: Jungfrauregion
    url: https://jungfrauregion.swiss
  - name: Viamala
    url: https://viamala.ch/
  - name: Appenzellerland
    url: https://appenzellerland.ch
  - name: Toggenburg
    url: https://toggenburg.swiss
  - name: Winterthur
    url: https://winterthur.com
  - name: Herzroute
    url: https://herzroute.ch
  - name: Ostschweiz
    url: https://ostschweiz.ch
  - name: Ogfs
    url: https://ogfs.ch


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: tsolenthaler.github.io/DashboardWebsitesTSO/
  # baseUrl: /your-repo-name
  logoUrl: https://tso.ch/assets/images/j/TSO_Logo-zkcz1ye4dqz9yna.svg
  favicon: https://tso.ch/files/design_assets/alt-tsoag-theme/img/favicon.ico
  name: Status Page
  introTitle: "Status Page der TSO AG"
  introMessage: "Hier findest du den aktuellen Status unserer Websites. Wir überwachen die Erreichbarkeit und Leistung unserer Online-Dienste, um sicherzustellen, dass sie jederzeit verfügbar sind. Wenn es Probleme gibt, arbeiten wir schnell daran, sie zu beheben. Vielen Dank für dein Verständnis!"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
